spring:
  datasource:
    url: jdbc:h2:mem:~/ejercicioJava
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      platform: h2
      mode: always
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    com.ejercicioyava.microservicio.controllers: DEBUG